## Measure of Central tendency

In [1]:
import pandas as pd 
from scipy import stats

In [19]:
data_path="/Users/innovapathinc/Desktop/Stats /house_dataset.csv"
house_df=pd.read_csv(data_path)
house_df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [11]:
house_df.shape

(21600, 21)

In [6]:
house_df=house_df.dropna(subset=["Sale Price","Flat Area (in Sqft)"])

In [12]:
mean_Sale_price=house_df["Sale Price"].mean()
mean_Flat_Area=house_df["Flat Area (in Sqft)"].mean()

In [13]:
print(mean_Flat_Area)
mean_Sale_price

2079.943333333333

540233.9350925926

In [14]:
median_Sale_price=house_df["Sale Price"].median()
median_Flat_Area=house_df["Flat Area (in Sqft)"].median()

In [15]:
print(median_Sale_price)
median_Flat_Area

450000.0

1910.0

In [17]:
mode_Sale_price=house_df["Sale Price"].mode()
mode_Flat_Area=house_df["Flat Area (in Sqft)"].mode()

In [18]:
print(mode_Sale_price)
mode_Flat_Area

0    350000.0
Name: Sale Price, dtype: float64

0    1300.0
Name: Flat Area (in Sqft), dtype: float64

## Measure of spread or variability

In [20]:
data=pd.read_csv("/Users/innovapathinc/Desktop/Stats /house_dataset.csv")

In [22]:
df=pd.DataFrame(data)
df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

### Range 
-Calculate Range: Difference between Max and Min

In [23]:
range_sale_price = df['Sale Price'].max() - df['Sale Price'].min()
range_flat_area = df['Flat Area (in Sqft)'].max() - df['Flat Area (in Sqft)'].min()
print(range_sale_price)
print(range_flat_area)

7625000.0
13250.0

### Variance 
Calculate Variance: Average of squared differences from the mean

In [25]:
variance_sale_price = df['Sale Price'].var()
variance_flat_area = df['Flat Area (in Sqft)'].var()

print(variance_sale_price)
print(variance_flat_area)

134974673250.80968
843619.4655108906

### Standard Deviation 
calculate Standard Deviation: Square root of the variance

In [26]:
std_dev_sale_price = df['Sale Price'].std()
std_dev_flat_area = df['Flat Area (in Sqft)'].std()
print(std_dev_sale_price)
print(std_dev_flat_area)

367388.99446065293
918.4875968192987

In [27]:
# Display the results
print(f"Range of Sale Price: {range_sale_price}")
print(f"Range of Flat Area: {range_flat_area}")
print(f"Variance of Sale Price: {variance_sale_price}")
print(f"Variance of Flat Area: {variance_flat_area}")
print(f"Standard Deviation of Sale Price: {std_dev_sale_price}")
print(f"Standard Deviation of Flat Area: {std_dev_flat_area}")

Range of Sale Price: 7625000.0
Range of Flat Area: 13250.0
Variance of Sale Price: 134974673250.80968
Variance of Flat Area: 843619.4655108906
Standard Deviation of Sale Price: 367388.99446065293
Standard Deviation of Flat Area: 918.4875968192987